name: Tests

on: [pull_request]

jobs:
  test:
    name: build-and-test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install protoc
      run: sudo apt-get update -qqq && sudo apt-get install -y protobuf-compiler
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          override: true
          components: rustfmt, clippy
    - name: Build
      run: DOCKER_BUILD=1 cargo build --all
    - name: Run tests
      run: DOCKER_BUILD=1 cargo test


  fmt:
    name: fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: rustup component add rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  clippy:
    name: clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: rustup component add clippy
      - name: Install protoc
        run: sudo apt-get install protobuf-compiler
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all --all-targets -- -D warnings
